### ISSUE TITLE
Uncaught error usage of PackageManager in TYPO3 12

### ISSUE THREAD

**Issue by josefglatz** [networkteam/sentry_client#89]
URL while it occured: `https://customer.dev.foo/typo3/ajax/icons" `

```
Error: Uncaught Error: Typed static property TYPO3\CMS\Core\Utility\ExtensionManagementUtility::$packageManager must not be accessed before initialization in /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Utility/ExtensionManagementUtility.php:110
Stack trace:
#0 /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(2596): TYPO3\CMS\Core\Utility\ExtensionManagementUtility::resolvePackagePath()
#1 /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Controller/ErrorPageController.php(46): TYPO3\CMS\Core\Utility\GeneralUtility::getFileAbsFileName()
#2 /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(2969): TYPO3\CMS\Core\Controller\ErrorPageController->__construct()
#3 /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Error/ProductionExceptionHandler.php(64): TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance()
#4 /usr/www/users/customerdev/app/releases/20230913112216/vendor/typo3/cms-core/Classes/Error/AbstractExceptionHandler.php(71): TYPO3\CMS\Core\Error\ProductionExceptionHandler->echoExceptionWeb()
#5 /usr/www/users/customerdev/app/releases/20230913112216/vendor/networkteam/sentry-client/Classes/ProductionExceptionHandler.php(22): TYPO3\CMS\Core\Error\AbstractExceptionHandler->handleException()
#6 [internal function]: Networkteam\SentryClient\ProductionExceptionHandler->handleException()
#7 {main}
  thrown
```

**Comment by christophlehmann** [comment]
Can you check v5.0.0?

**Comment by josefglatz** [comment]
Ah! Overseen the new version tag.

Is it on purpose, that my root composer.json of the project does also require `php-http/guzzle7-adapter` when requiring version 5 of sentry_client?

<img width="404" alt="image" src="https://github.com/networkteam/sentry_client/assets/2861556/dfc707af-49f5-4410-8917-356550077b99">

**Comment by christophlehmann** [comment]
>Ah! Overseen the new version tag.

Freshly created ;-) Is it fixed?

>Is it on purpose, that my root composer.json of the project does also require php-http/guzzle7-adapter when requiring version 5 of sentry_client?

Yes, that is the consequence of #82
