### ISSUE TITLE
Uncaught Error: Typed static property

### ISSUE THREAD

**Issue by bartoszx** [networkteam/sentry_client#95]
Hello

I've tried everything but still have problem with this extension under v12.

What else I can check?

My error

```
[Fri Dec 22 08:55:16.316584 2023] [php:error] [pid 16] [client 127.0.0.1:40404] PHP Fatal error:  Uncaught Error: Typed static property TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::$packageManager must not be accessed before initialization in /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Utility/ExtensionManagementUtility.php:110\nStack trace:\n#0 /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(2613): TYPO3\\CMS\\Core\\Utility\\ExtensionManagementUtility::resolvePackagePath('EXT:core/Resour...')\n#1 /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Controller/ErrorPageController.php(46): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::getFileAbsFileName('EXT:core/Resour...')\n#2 /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Utility/GeneralUtility.php(2986): TYPO3\\CMS\\Core\\Controller\\ErrorPageController->__construct()\n#3 /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Error/ProductionExceptionHandler.php(63): TYPO3\\CMS\\Core\\Utility\\GeneralUtility::makeInstance('TYPO3\\\\CMS\\\\Core\\\\...')\n#4 /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Error/AbstractExceptionHandler.php(72): TYPO3\\CMS\\Core\\Error\\ProductionExceptionHandler->echoExceptionWeb(Object(TypeError))\n#5 /home/hdai/d2v12/vendor/networkteam/sentry-client/Classes/ProductionExceptionHandler.php(29): TYPO3\\CMS\\Core\\Error\\AbstractExceptionHandler->handleException(Object(TypeError))\n#6 [internal function]: Networkteam\\SentryClient\\ProductionExceptionHandler->handleException(Object(TypeError))\n#7 {main}\n  thrown in /home/hdai/d2v12/vendor/typo3/cms-core/Classes/Utility/ExtensionManagementUtility.php on line 110
```

Typo3 v12

composer.json
```
		"networkteam/sentry-client": "^5.0",
		"php-http/guzzle7-adapter": "^1.0",
```

system/additional.php
```
$GLOBALS['TYPO3_CONF_VARS']['EXTENSIONS']['sentry_client']['dsn'] = 'https://***@sentry/17';

if (TYPO3\CMS\Core\Core\Environment::getContext()->isProduction()) {
    // Register exception handler
    $GLOBALS['TYPO3_CONF_VARS']['SYS']['productionExceptionHandler'] = Networkteam\SentryClient\ProductionExceptionHandler::class;
    // Forward log messages to Sentry
    $GLOBALS['TYPO3_CONF_VARS']['LOG']['writerConfiguration'] = [
        \TYPO3\CMS\Core\Log\LogLevel::ERROR => [
            \Networkteam\SentryClient\SentryLogWriter::class => [],
        ],
    ];
    // Set sentry/sentry options
    $GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['sentry_client']['options']['server_name'] = 'node1';
}
```

**Comment by christophlehmann** [comment]
Is #92 related?

**Comment by bartoszx** [comment]
Yes. Thanks
